version: '3.9'

services:
  blog-api:
    build: .
    container_name: blog-api
    ports:
      - '4001:3001'
    env_file:
      - .env
    volumes:
      - ./uploads:/app/uploads
    restart: unless-stopped
